### ISSUE TITLE
helpコマンドの結果をDMまたは本人のみ見える形で送ってほしい

### ISSUE THREAD

**Issue by gimKondo** [cahlchang/CoCBotKP#87]
## 概要
- #85 でヘルプが充実したが、このまま使うと一気にチャンネル内のログが流れてしまう
- DMかOnly Visible Youなメッセージとして返されると良い
  - コマンド実行者のログも流れてほしくないと考えるとDMが良い気がする

**Comment by cahlchang** [comment]
あ、Only Visible Youで考えてましたけど、DM（というかAppからの送信）だといいかもですねー
そっちで考えてみますねー

**Comment by cahlchang** [comment]
https://github.com/cahlchang/CoCBotKP/pull/88

IM（DM)で送る形にしてみました。
現状のチャンネルに飛ばす機能も（他の人の説明用に）残しています。
このような実装でいかがでしょうか？
